// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadFile(arg1:number):Promise<string>;

export function ListFiles():Promise<Array<main.FileCard>>;

export function UploadFile():Promise<main.FileCard>;
