// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function UploadFile() {
  return window['go']['main']['App']['UploadFile']();
}
